@urlPrefix = http://localhost:9000
@productId = product-3
@name = Product 3
@description = Product 3 description
@price = 30.0

### Create a product

POST {{urlPrefix}}/product/{{productId}}/create
Content-Type: application/json

{
  "productId": "{{productId}}",
  "name": "{{name}}",
  "description": "{{description}}",
  "price": {{price}}
}

### Get a product

GET {{urlPrefix}}/product/{{productId}}

### query products by product id

GET {{urlPrefix}}/products/by-product-id/{{productId}}
