@urlPrefix = http://localhost:9000
@cartId = cart-1
@productId = product-1
@quantity = 1

### add item to shopping cart

PUT {{urlPrefix}}/shopping-cart/{{cartId}}/add-item
Content-Type: application/json

{
  "cartId": "{{cartId}}",
  "item": {
    "productId": "{{productId}}",
    "quantity": {{quantity}}
  }
}

### checkout shopping cart

PUT {{urlPrefix}}/shopping-cart/{{cartId}}/checkout
Content-Type: application/json

{
  "cartId": "{{cartId}}"
}

### get shopping cart

GET {{urlPrefix}}/shopping-cart/{{cartId}}
